version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8910:80"
    working_dir: /code
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: reservation_system
    working_dir: /code
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code